
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace tcord {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class MyView : Terminal.Gui.Views.Window {
        
        private Terminal.Gui.Views.FrameView serverView;
        
        private Terminal.Gui.Views.ListView serverList;
        
        private Terminal.Gui.Views.FrameView channels;
        
        private Terminal.Gui.Views.ListView channelListView;
        
        private Terminal.Gui.Views.FrameView msgBoard;
        
        private Terminal.Gui.Views.ListView msgBoardTexts;
        
        private Terminal.Gui.Views.FrameView discordTokenInputWindow;
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.TextField inputField;
        
        private Terminal.Gui.Views.Button okButton;
        
        private Terminal.Gui.Views.TextField messageInput;
        
        private Terminal.Gui.Views.MenuBar menuBar;
        
        private Terminal.Gui.Views.MenuBarItem fileF9Menu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.Views.MenuBar();
            this.messageInput = new Terminal.Gui.Views.TextField();
            this.okButton = new Terminal.Gui.Views.Button();
            this.inputField = new Terminal.Gui.Views.TextField();
            this.label = new Terminal.Gui.Views.Label();
            this.discordTokenInputWindow = new Terminal.Gui.Views.FrameView();
            this.msgBoardTexts = new Terminal.Gui.Views.ListView();
            this.msgBoard = new Terminal.Gui.Views.FrameView();
            this.channelListView = new Terminal.Gui.Views.ListView();
            this.channels = new Terminal.Gui.Views.FrameView();
            this.serverList = new Terminal.Gui.Views.ListView();
            this.serverView = new Terminal.Gui.Views.FrameView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "mainUI";
            this.serverView.Width = 11;
            this.serverView.Height = Dim.Fill(0);
            this.serverView.X = 0;
            this.serverView.Y = 1;
            this.serverView.Visible = true;
            this.serverView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.serverView.CanFocus = true;
            this.serverView.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.serverView.Data = "serverView";
            this.serverView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.serverView.Title = "Servers";
            this.Add(this.serverView);
            this.serverList.Width = 9;
            this.serverList.Height = Dim.Fill(0);
            this.serverList.X = 0;
            this.serverList.Y = 0;
            this.serverList.Visible = true;
            this.serverList.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.serverList.CanFocus = true;
            this.serverList.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.serverList.Data = "serverList";
            this.serverList.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.serverList.Source = new Terminal.Gui.Views.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "Server1",
                            "Server2"}));
            this.serverList.AllowsMarking = false;
            this.serverList.AllowsMultipleSelection = true;
            this.serverView.Add(this.serverList);
            this.channels.Width = 26;
            this.channels.Height = Dim.Fill(0);
            this.channels.X = 11;
            this.channels.Y = 1;
            this.channels.Visible = true;
            this.channels.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.channels.CanFocus = true;
            this.channels.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.channels.Data = "channels";
            this.channels.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.channels.Title = "Channels";
            this.Add(this.channels);
            this.channelListView.Width = Dim.Fill(0);
            this.channelListView.Height = Dim.Fill(0);
            this.channelListView.X = 0;
            this.channelListView.Y = 0;
            this.channelListView.Visible = true;
            this.channelListView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.channelListView.CanFocus = true;
            this.channelListView.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.channelListView.Data = "channelListView";
            this.channelListView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.channelListView.Source = new Terminal.Gui.Views.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "Item1",
                            "Item2",
                            "Item3"}));
            this.channelListView.AllowsMarking = false;
            this.channelListView.AllowsMultipleSelection = true;
            this.channels.Add(this.channelListView);
            this.msgBoard.Width = Dim.Fill(0);
            this.msgBoard.Height = Dim.Fill(3);
            this.msgBoard.X = 37;
            this.msgBoard.Y = 1;
            this.msgBoard.Visible = true;
            this.msgBoard.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.msgBoard.CanFocus = true;
            this.msgBoard.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.msgBoard.Data = "msgBoard";
            this.msgBoard.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.msgBoard.Title = "Messages";
            this.Add(this.msgBoard);
            this.msgBoardTexts.Width = Dim.Fill(0);
            this.msgBoardTexts.Height = Dim.Fill(0);
            this.msgBoardTexts.X = 0;
            this.msgBoardTexts.Y = 0;
            this.msgBoardTexts.Visible = true;
            this.msgBoardTexts.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.msgBoardTexts.CanFocus = true;
            this.msgBoardTexts.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.msgBoardTexts.Data = "msgBoardTexts";
            this.msgBoardTexts.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.msgBoardTexts.Source = new Terminal.Gui.Views.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "Item1",
                            "Item2",
                            "Item3"}));
            this.msgBoardTexts.AllowsMarking = false;
            this.msgBoardTexts.AllowsMultipleSelection = true;
            this.msgBoard.Add(this.msgBoardTexts);
            this.discordTokenInputWindow.Width = 50;
            this.discordTokenInputWindow.Height = 20;
            this.discordTokenInputWindow.X = Pos.Center();
            this.discordTokenInputWindow.Y = Pos.Center();
            this.discordTokenInputWindow.Visible = false;
            this.discordTokenInputWindow.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.discordTokenInputWindow.CanFocus = true;
            this.discordTokenInputWindow.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.discordTokenInputWindow.Data = "discordTokenInputWindow";
            this.discordTokenInputWindow.TextAlignment = Terminal.Gui.ViewBase.Alignment.Fill;
            this.discordTokenInputWindow.Title = "Input Discord Token";
            this.Add(this.discordTokenInputWindow);
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = Pos.Center();
            this.label.Y = 4;
            this.label.Visible = false;
            this.label.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label.CanFocus = false;
            this.label.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.label.Data = "label";
            this.label.Text = "Discord Passwordless Login";
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.discordTokenInputWindow.Add(this.label);
            this.inputField.Width = 32;
            this.inputField.Height = 1;
            this.inputField.X = Pos.Center();
            this.inputField.Y = Pos.Center();
            this.inputField.Visible = true;
            this.inputField.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.inputField.CanFocus = true;
            this.inputField.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.inputField.Secret = true;
            this.inputField.Data = "inputField";
            this.inputField.Text = "";
            this.inputField.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.discordTokenInputWindow.Add(this.inputField);
            this.okButton.Width = Dim.Auto();
            this.okButton.Height = Dim.Auto();
            this.okButton.X = Pos.Center();
            this.okButton.Y = 13;
            this.okButton.Visible = true;
            this.okButton.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.okButton.CanFocus = true;
            this.okButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.okButton.Data = "okButton";
            this.okButton.Text = "Ok";
            this.okButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.okButton.IsDefault = false;
            this.discordTokenInputWindow.Add(this.okButton);
            this.messageInput.Width = Dim.Fill(1);
            this.messageInput.Height = 1;
            this.messageInput.X = 39;
            this.messageInput.Y = Pos.AnchorEnd(2);
            this.messageInput.Visible = true;
            this.messageInput.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.messageInput.CanFocus = true;
            this.messageInput.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.messageInput.Secret = false;
            this.messageInput.Data = "messageInput";
            this.messageInput.Text = "Send Message...";
            this.messageInput.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.messageInput);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.menuBar.CanFocus = false;
            this.menuBar.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.fileF9Menu = new Terminal.Gui.Views.MenuBarItem();
            this.fileF9Menu.Title = "_File (F9)";
            this.editMeMenuItem = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.editMeMenuItem.Data = "editMeMenuItem";
            this.fileF9Menu.Children = new Terminal.Gui.Views.MenuItem[] {
                    this.editMeMenuItem};
            this.menuBar.Menus = new Terminal.Gui.Views.MenuBarItem[] {
                    this.fileF9Menu};
            this.Add(this.menuBar);
        }
    }
}
